# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: amitrke/node-appengine:latest
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome

    working_directory: ~/ngrke

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - ngrke-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - ngrke-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: ngrke-{{ checksum "package.json" }}
      
      - run: yarn build